services:
  # Base de datos
  db:
    image: mysql:8.0
    container_name: mysql_alumno
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accesodatos
    # Esto evita problemas de conexión con drivers de Java antiguos/nuevos
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - db_data:/var/lib/mysql

  # Contenedor del alumno
  java_dev:
    build: .
    container_name: java_alumno
    tty: true
    volumes:
      - ./src:/app
    depends_on:
      - db
    # Host para conectar desde Java
    environment:
      DB_HOST: db

volumes:
  db_data: