services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=paso
    volumes:
      - ~/OdooDev/dataPG:/var/lib/postgresql/data
    networks:
      - shared_network
  odoo:
    image: odoo:16
    container_name: odoo_16
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=paso
    ports:
      - '8069:8069'
    volumes:
      - ~/OdooDev/volumesOdoo/addons:/mnt/extra-addons
      - ~/OdooDev/volumesOdoo/filestore:/var/lib/odoo/filestore
    depends_on:
      - postgres
    command: --dev=all
    networks:
      - shared_network

networks:
  shared_network:
    external: true