services:
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: ${MINIO_ADDRESS}
      MINIO_CONSOLE_ADDRESS: ${MINIO_CONSOLE_ADDRESS}
    command: minio server /data

    
networks:
  shared-network:
    external: true
    name: ${DOCKER_NETWORK_NAME:-shared-network}