services:
  minio1:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    hostname: minio1
    container_name: minio1
    volumes:
      - ./minio1/data1:/data1
      - ./minio1/data2:/data2
      - ./minio1/data3:/data3
      - ./minio1/data4:/data4
    ports:
      - "9001:9000"  # API S3
      - "9091:9090"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=Villabalter1
    command: server http://minio{1...4}/data{1...4} --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    hostname: minio2
    container_name: minio2
    volumes:
      - ./minio2/data1:/data1
      - ./minio2/data2:/data2
      - ./minio2/data3:/data3
      - ./minio2/data4:/data4
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=Villabalter1
    command: server http://minio{1...4}/data{1...4} --console-address ":9090"
    depends_on:
      - minio1

  minio3:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    hostname: minio3
    container_name: minio3
    volumes:
      - ./minio3/data1:/data1
      - ./minio3/data2:/data2
      - ./minio3/data3:/data3
      - ./minio3/data4:/data4
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=Villabalter1
    command: server http://minio{1...4}/data{1...4} --console-address ":9090"
    depends_on:
      - minio1

  minio4:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    hostname: minio4
    container_name: minio4
    volumes:
      - ./minio4/data1:/data1
      - ./minio4/data2:/data2
      - ./minio4/data3:/data3
      - ./minio4/data4:/data4
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=Villabalter1
    command: server http://minio{1...4}/data{1...4} --console-address ":9090"
    depends_on:
      - minio1

networks:
  default:
    name: minio_network
    driver: bridge



    