services:
  namenode:
    image: vega90/hadoop-namenode:1.0
    container_name: namenode
    hostname: namenode
    command: bash -c /etc/start.sh
    networks: 
      - shared-network
    ports:
      - 9870:9870    # Hadoop NameNode Web UI
      - 7777:8888    # Jupyter
      - 10000:10000  # Hive
      - 10002:10002  # HiveServer2
    volumes: 
      - ./notebooks:/media/notebooks
    tty: true
    stdin_open: true

  yarnmanager:
    image: vega90/hadoop-yarn:1.0
    container_name: yarnmanager
    hostname: yarnmanager
    networks: 
      - shared-network
    ports:
      - 8088:8088    # YARN Resource Manager Web UI
      - 19888:19888  # JobHistory Web UI

  datanode1:
    image: vega90/hadoop-datanode:1.0
    container_name: datanode1
    hostname: datanode1
    networks: 
      - shared-network

  datanode2:
    image: vega90/hadoop-datanode:1.0
    container_name: datanode2
    hostname: datanode2
    networks: 
      - shared-network 

  datanode3:
    image: vega90/hadoop-datanode:1.0
    container_name: datanode3
    hostname: datanode3
    networks: 
      - shared-network

  datanode4:
    image: vega90/hadoop-datanode:1.0
    container_name: datanode4
    hostname: datanode4
    networks: 
      - shared-network


networks:
  shared-network:
    external: true