services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter_datascience
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    working_dir: /home/jovyan/work
    networks:
      - shared-network
networks:
  shared-network:
    external: true